### ISSUE TITLE
terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by marionebl** [tangramxyz/tangram#1]
Given an input file `input.csv` 

```csv
content,label
some-text,a
other-text,b
```

The following invocation

```
$ tangram --version
$ tangram train --file input.csv --target label --output output.tangram
```

fails with

```
✅ Inferring train table columns. 0ms
✅ Loading train table. 0ms
✅ Shuffling. 0ms
✅ Computing train stats. 0ms
thread panicked while panicking. aborting.
fish: 'tangram  train --file input.csv…' terminated by signal SIGILL (Illegal instruction)
```

**Comment by isabella** [comment]
Hi @marionebl thank you so much for filing the first issue! The terrible crash you found was caused by a divide-by-zero bug in the code that renders training progress to the terminal. With the small dataset you provided, the train/test split produced zero rows in the test set. Yesterday we released version 0.4.0 which defends against this divide-by-zero and also refuses to train on datasets with very few rows.
