### ISSUE TITLE
502 bad gateway when attempting to view model on app.tangram.xyz, or local version

### ISSUE THREAD

**Issue by matt1tk** [tangramxyz/tangram#5]
![image](https://user-images.githubusercontent.com/54869024/125339077-7ed17380-e340-11eb-85de-d3dacbcbe0bd.png)

Local version does this upon clicking upload: 
![image](https://user-images.githubusercontent.com/54869024/125339290-b17b6c00-e340-11eb-9db1-938b081e2697.png)
but the model appears in the list: 
![image](https://user-images.githubusercontent.com/54869024/125339325-b6d8b680-e340-11eb-873c-49d57be64183.png)
but then clicking it once again results in this: 
![image](https://user-images.githubusercontent.com/54869024/125339348-bfc98800-e340-11eb-8bd8-3006b0dfcc29.png)

This is the output of the local version: `thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/app/pages/repos/_/models/_/index/server/get.rs:435:30` 

The offending code: https://github.com/tangramxyz/tangram/blob/main/crates/app/pages/repos/_/models/_/index/server/get.rs#L435

**Comment by nitsky** [comment]
Hey @matt1tk, thanks for the report, I found it in the server logs for app.tangram.xyz and reproduced it. From the line of code, it looks like we have erroneously produced an `NaN` for the feature importances for one of the features to your model. We use Rust's `PartialCmp` to compare feature importances for displaying a chart in the app, and are unwrapping when the comparison fails, because we assume they can never be `NaN`. I'm investigating further now and will get back to you ASAP.

**Comment by nitsky** [comment]
@matt1tk In the dataset you provided, 100% of the target column values were `true`, so the feature importances really should be `NaN`, because each of the trees in the GBDT model just has a single node with no splits.

I updated the code to fail gracefully in this case and not display the feature contributions chart. This change has been pushed to app.tangram.xyz where you can view your model now. For running the app locally, this will be part of the next release, or you can build from source. 

I understand that this was an example dataset, but I suggest training a new model with a dataset where the target column has more than one value.

**Comment by matt1tk** [comment]
![image](https://user-images.githubusercontent.com/54869024/125371863-3da58780-e371-11eb-955f-89bdaced1405.png)

I forgot to test this before using it, lol, apparently oorandom's range includes lower bound but excludes upper bound, so this code always rot13'd the text. I don't know how I didn't catch this! Thanks!

**Comment by nitsky** [comment]
@matt1tk no problem, thanks for inadvertently producing an edge case that revealed a bad assumption in our code! We should also add a warning before training if the dataset is imbalanced.
